### ISSUE TITLE
Configure link to define custom homeserver/identity server automatically from `https://app.element.io/mobile_guide/` does not work (`mobile.element.io`)

### ISSUE THREAD

**Issue by MadLittleMods** [element-hq/element-android#5748] opened 2022-04-12 19:51 UTC
### Steps to reproduce

1. Have Element Android installed and signed out
2. Visit https://app.element.io/mobile_guide/
3. Click the **Configure** button
4. Notice how it just redirects to https://mobile.element.io/?hs_url=https%3A%2F%2Fmatrix-client.matrix.org%2F&is_url=https%3A%2F%2Fvector.im%2F instead of being handled by the Android app

---

With Element Android installed on the sign in screen.

Press configure | Just redirects me to `mobile.element.io` and pressing "Try again" does nothing
--- | ---
<img src="https://user-images.githubusercontent.com/558581/163031998-e8ab9ea1-6591-4677-b6db-945f2179c495.png" width="270"> | <img src="https://user-images.githubusercontent.com/558581/163039400-81a3b02b-a496-4d56-817c-8467f4a5ed99.png" width="270">

#### What did you expect?

The Android app opens with the custom homeserver and identity server filled in

#### What happened instead?

Just redirects to https://mobile.element.io/?hs_url=https%3A%2F%2Fmatrix-client.matrix.org%2F&is_url=https%3A%2F%2Fvector.im%2F which tells me to update my app (which is already the latest) and try again which also does nothing.

### Your phone model

Pixel 4a

### Operating system version

Android 12

### Application version and app store

Element version 1.4.11

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by daniellekirkwood** [comment] 2022-05-31 13:41
@ouchadam to check if this has been completed already

**Comment by ouchadam** [comment] 2022-05-31 14:10
I can confirm mobile.element.io deeplink were fixed with https://github.com/vector-im/element-android/pull/6036

**Comment by MadLittleMods** [comment] 2022-05-31 20:00
@ouchadam This still does not work for me (same as issue description), Element Android 1.4.16

**Comment by MadLittleMods** [comment] 2022-06-01 08:16
@ouchadam I don't think the intent is registered at all for me.

Chrome doesn't have any open by default settings.

Element Open by default settings | Holding on the Configure link doesn't give me the open with options
--- | ---
<img src="https://user-images.githubusercontent.com/558581/171358853-b1e7162b-d891-478a-b7b1-ac1036c5b24e.png" width="540"> | <img src="https://user-images.githubusercontent.com/558581/171358948-9b7784c9-9b34-4a1d-b8fc-dc949ce4bb56.png" width="540">

**Comment by ouchadam** [comment] 2022-06-01 08:32
ah it looks like we're hitting the web intent change in android 12 https://developer.android.com/about/versions/12/behavior-changes-all#web-intent-resolution

we'll need element.io to host an `https://element.io/.well-known/assetlinks.json` to confirm the Element app is approved to handle the url links

**Comment by davidrtlt** [comment] 2022-09-02 05:35
Hello. As someone not familiar with open source, can you clue me in on the timeline where this deep-link functionality will work on Android?

Would love to deploy Element for our organization, and giving users a link that pre-fills the home server is going to be a must (the users are low-tech)

I don't mean this to sound demanding, just wondering if someone can decipher the activity here and let me know if an ETA to release is known.

Thank you

**Comment by MadLittleMods** [comment] 2022-09-02 16:39
@davidrtlt The PR to fix this, https://github.com/vector-im/element-android/pull/6225, is currently waiting on a change to `element.io` itself (it needs `/.well-known/assetlinks.json` to be present) which the Ops team needs to tackle, https://github.com/matrix-org/matrix-ansible-private/issues/5223 (internal link). There is no ETA on when that change will happen.

**Comment by davidrtlt** [comment] 2022-09-02 18:28
@MadLittleMods thanks for the insight. Do you know if there is a workaround, or another way, to getting the home server prefilled for new users?

**Comment by MadLittleMods** [comment] 2022-09-02 18:53
@davidrtlt You can setup `/.well-known/matrix/client` on your own homeserver, https://spec.matrix.org/v1.1/client-server-api/#well-known-uri

> **Client Server discovery** (`/.well-known/matrix/client`) -- assists programs that you use to connect to your server (e.g. Element), so that they can make it more convenient for you by automatically configuring the "Homeserver URL" and "Identity Server URL" addresses. Learn more in [Introduction to Client Server Discovery](#introduction-to-client-server-discovery)
>
> *-- https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md*

It's the first time that I'm looking at it or knowing about it so I don't have more details than those docs.

**Comment by davidrtlt** [comment] 2022-09-02 19:17
@MadLittleMods I really appreciate you pointing me in this direction. I will try this out. Have a wonderful weekend.

**Comment by albanbruder** [comment] 2024-02-05 09:44
Can you give an ETA for when this will be fixed?

Currently only [element.io](https://element.io/.well-known/assetlinks.json) is serving the assetlinks.json file. However, for deep linking to work correctly, at least the following domains must also serve the file:

- mobile.element.io
- app.element.io
- matrix.to

Other URLs that are registered but not verified by the Element Android app:

- staging.element.io
- develop.element.io
- riot.im

This is a showstopper for our userbase, as autoconfiguration via link/qr code is a huge relief for less tech-savvy users.

**Closed** 2024-05-02 14:58 UTC
Labels: T-Defect, Z-FTUE, A-Deep-link, S-Minor, O-Uncommon, Z-WTF, A-Onboarding
